name: My First GitHub Action

on:
  push:

jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Welcome Message
        run: |
          echo "Welcome to my first GitHub Action!"
          ls
          cat README.md
          